# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName("AppWindow")
        AppWindow.resize(500, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Photos/Pictures/Icons/Lumicons ico pack/System/Device Keyboard.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AppWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.text_error = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_error.sizePolicy().hasHeightForWidth())
        self.text_error.setSizePolicy(sizePolicy)
        self.text_error.setMinimumSize(QtCore.QSize(0, 50))
        self.text_error.setText("")
        self.text_error.setAlignment(QtCore.Qt.AlignCenter)
        self.text_error.setObjectName("text_error")
        self.verticalLayout_2.addWidget(self.text_error)
        spacerItem1 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_version = QtWidgets.QLabel(self.centralwidget)
        self.text_version.setObjectName("text_version")
        self.horizontalLayout.addWidget(self.text_version)
        self.text_FAQ = QtWidgets.QLabel(self.centralwidget)
        self.text_FAQ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_FAQ.setOpenExternalLinks(True)
        self.text_FAQ.setObjectName("text_FAQ")
        self.horizontalLayout.addWidget(self.text_FAQ)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        AppWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AppWindow)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        _translate = QtCore.QCoreApplication.translate
        AppWindow.setWindowTitle(_translate("AppWindow", "NAZVA"))
        self.text_version.setText(_translate("AppWindow", "version 1.5.0"))
        self.text_FAQ.setText(_translate("AppWindow", "<html><head/><body><p><a href=\"http://www.qtcentre.org\"><span style=\" text-decoration: underline; color:#0000ff;\">F.A.Q.</span></a></p></body></html>"))
