# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(500, 656)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setMinimumSize(QtCore.QSize(350, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Photos/Pictures/Icons/Lumicons ico pack/System/Device Keyboard.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setStyleSheet("color: blue;\n"
"outline: none;\n"
"border: 0;\n"
"background: transparent;\n"
"text-decoration: underline;")
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout_2.addWidget(self.btn_back, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.text_error = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_error.sizePolicy().hasHeightForWidth())
        self.text_error.setSizePolicy(sizePolicy)
        self.text_error.setMinimumSize(QtCore.QSize(0, 50))
        self.text_error.setText("")
        self.text_error.setAlignment(QtCore.Qt.AlignCenter)
        self.text_error.setObjectName("text_error")
        self.verticalLayout_2.addWidget(self.text_error)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_password.sizePolicy().hasHeightForWidth())
        self.line_password.setSizePolicy(sizePolicy)
        self.line_password.setMinimumSize(QtCore.QSize(0, 30))
        self.line_password.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_password.setObjectName("line_password")
        self.gridLayout.addWidget(self.line_password, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_login.sizePolicy().hasHeightForWidth())
        self.line_login.setSizePolicy(sizePolicy)
        self.line_login.setMinimumSize(QtCore.QSize(0, 30))
        self.line_login.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_login.setObjectName("line_login")
        self.gridLayout.addWidget(self.line_login, 1, 1, 1, 1)
        self.text_password = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_password.sizePolicy().hasHeightForWidth())
        self.text_password.setSizePolicy(sizePolicy)
        self.text_password.setMinimumSize(QtCore.QSize(0, 50))
        self.text_password.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.text_password.setObjectName("text_password")
        self.gridLayout.addWidget(self.text_password, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.text_login = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_login.sizePolicy().hasHeightForWidth())
        self.text_login.setSizePolicy(sizePolicy)
        self.text_login.setMinimumSize(QtCore.QSize(0, 50))
        self.text_login.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.text_login.setObjectName("text_login")
        self.gridLayout.addWidget(self.text_login, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_forgot_pass = QtWidgets.QLabel(self.centralwidget)
        self.text_forgot_pass.setObjectName("text_forgot_pass")
        self.horizontalLayout_2.addWidget(self.text_forgot_pass)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_2.addWidget(self.btn_login)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_version = QtWidgets.QLabel(self.centralwidget)
        self.text_version.setObjectName("text_version")
        self.horizontalLayout.addWidget(self.text_version)
        self.text_FAQ = QtWidgets.QLabel(self.centralwidget)
        self.text_FAQ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_FAQ.setOpenExternalLinks(True)
        self.text_FAQ.setObjectName("text_FAQ")
        self.horizontalLayout.addWidget(self.text_FAQ)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "NAZVA"))
        self.btn_back.setText(_translate("LoginWindow", "❮ back"))
        self.text_password.setText(_translate("LoginWindow", "password:"))
        self.text_login.setText(_translate("LoginWindow", "login: "))
        self.text_forgot_pass.setText(_translate("LoginWindow", "Forgot password"))
        self.btn_login.setText(_translate("LoginWindow", "Login"))
        self.text_version.setText(_translate("LoginWindow", "version 1.5.0"))
        self.text_FAQ.setText(_translate("LoginWindow", "<html><head/><body><p><a href=\"http://www.qtcentre.org\"><span style=\" text-decoration: underline; color:#0000ff;\">F.A.Q.</span></a></p></body></html>"))


def run_app():
    pass



if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())






















